### ISSUE TITLE
Menu items exist for packages that are not installed

### ISSUE THREAD

**Issue by mattyjones** [BlackArch/blackarch-config-awesome#5]
In reference to [blackarch #2712](https://github.com/BlackArch/blackarch/issues/2712). There should be a way to dynamically generate the blackarch menu based on what packages and groups are installed. The heavy lifting is already done by having a master list of packages available in the repo but that list would also need to be maintained.

Having packages listed that are not installed and needing to wade through the menu of cruft is frustrating, especially for people used to a lightweight and purpose-built OS/WM.

**Comment by Edu4rdSHL** [comment]
Tracking this issue in blackarch/blackarch as it affects all Window Managers.
